const { GoogleGenAI, Type } = require("@google/genai");
const { z } = require("zod");
const { zodToJsonSchema } = require("zod-to-json-schema");
const puppeteer = require("puppeteer");

const ai = new GoogleGenAI({
  apiKey: process.env.GOOGLE_GENAI_API_KEY,
});

const interviewReportSchema = z.object({
  matchScore: z
    .number()
    .min(0)
    .max(100)
    .describe(
      "A score between 0 and 100 indicating how well the candidate matches the job description.",
    ),

  technicalQuestions: z
    .array(
      z.object({
        question: z.string().describe("A technical interview question."),
        intention: z
          .string()
          .describe("Why the interviewer asks this question."),
        answer: z
          .string()
          .describe("A complete interview answer with key points."),
      }),
    )
    .min(10)
    .describe("At least 10 technical interview questions."),

  behavioralQuestions: z
    .array(
      z.object({
        question: z.string().describe("A behavioral interview question."),
        intention: z
          .string()
          .describe("Why the interviewer asks this question."),
        answer: z.string().describe("A complete behavioral interview answer."),
      }),
    )
    .min(5)
    .describe("At least 5 behavioral interview questions."),

  skillGaps: z
    .array(
      z.object({
        skill: z.string().describe("Missing or weak skill."),
        severity: z
          .enum(["low", "medium", "high"])
          .describe("Importance of this skill gap."),
      }),
    )
    .min(5)
    .describe("At least 5 skill gaps."),

  preparationPlan: z
    .array(
      z.object({
        day: z.number().describe("Day number."),
        focus: z.string().describe("Main topic to study."),
        tasks: z.array(z.string()).min(2).describe("Study tasks for the day."),
      }),
    )
    .length(7)
    .describe("A 7-day interview preparation plan."),

  title: z.string().describe("Job title."),
});

async function generateInterviewReport({
  resume,
  selfDescription,
  jobDescription,
}) {
  const prompt = `Generate an interview report for a candidate with the following details:
                        Resume: ${resume}
                        Self Description: ${selfDescription}
                        Job Description: ${jobDescription}              
`;

  const response = await ai.models.generateContent({
    model: "gemini-3-flash-preview",
    contents: prompt,
    config: {
      responseMimeType: "application/json",
      responseSchema: interviewReportSchema.toJSONSchema(),
    },
  });

  return JSON.parse(response.text);
}

async function generatePdfFromHtml(htmlContent) {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.setContent(htmlContent, { waitUntil: "networkidle0" });

  const pdfBuffer = await page.pdf({
    format: "A4",
    margin: {
      top: "20mm",
      bottom: "20mm",
      left: "15mm",
      right: "15mm",
    },
  });

  await browser.close();

  return pdfBuffer;
}

async function generateResumePdf({ resume, jobDescription, selfDescription }) {
  const resumePdfSchema = z.object({
    html: z
      .string()
      .describe(
        "The HTML content of the resume which can be converted to PDF using any library like puppeteer",
      ),
  });

  const prompt = `Generate resume for a candidate with the following details:
                        Resume: ${resume}
                        Self Description: ${selfDescription}
                        Job Description: ${jobDescription}

                        the response should be a JSON object with a single field "html" which contains the HTML content of the resume which can be converted to PDF using any library like puppeteer.
                        The resume should be tailored for the given job description and should highlight the candidate's strengths and relevant experience. The HTML content should be well-formatted and structured, making it easy to read and visually appealing.
                        The content of resume should be not sound like it's generated by AI and should be as close as possible to a real human-written resume.
                        you can highlight the content using some colors or different font styles but the overall design should be simple and professional.
                        The content should be ATS friendly, i.e. it should be easily parsable by ATS systems without losing important information.
                        The resume should not be so lengthy, it should ideally be 1-2 pages long when converted to PDF. Focus on quality rather than quantity and make sure to include all the relevant information that can increase the candidate's chances of getting an interview call for the given job description.
                    `;

  const response = await ai.models.generateContent({
    model: "gemini-3-flash-preview",
    contents: prompt,
    config: {
      responseMimeType: "application/json",
      responseSchema: resumePdfSchema.toJSONSchema(),
    },
  });

  const jsonContent = JSON.parse(response.text);

  const pdfBuffer = await generatePdfFromHtml(jsonContent.html);

  return pdfBuffer;
}

module.exports = { generateInterviewReport, generateResumePdf };
